# Generated by Django 2.2.4 on 2019-08-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NagiosChecks',
            new_name='NagiosCheck',
        ),
        migrations.RenameModel(
            old_name='NagiosContactgroupsMembers',
            new_name='NagiosContactgroupsMember',
        ),
        migrations.RemoveField(
            model_name='nagioscontactgroups',
            name='members',
        ),
    ]
