# Generated by Django 2.2.4 on 2019-08-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagioscontact',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nagioscontactgroup',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nagioshostgroup',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nagioshosttemplates',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nagiostimeperiods',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
