# Generated by Django 2.2.4 on 2019-08-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0002_auto_20190830_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nagioscontact',
            name='contactgroups',
        ),
        migrations.AddField(
            model_name='nagioscontactgroup',
            name='contacts',
            field=models.ManyToManyField(to='nagios.NagiosContact'),
        ),
    ]
