# Generated by Django 2.2.4 on 2019-08-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0003_auto_20190830_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nagiosservice',
            name='contact_groups',
        ),
        migrations.AddField(
            model_name='nagiosservice',
            name='contact_groups',
            field=models.ManyToManyField(to='nagios.NagiosContactGroup'),
        ),
        migrations.DeleteModel(
            name='NagiosServicesContactgroups',
        ),
    ]
