# Generated by Django 2.2.4 on 2019-08-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0004_auto_20190830_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='NagiosPlatform',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nagios_platforms',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='nagioshostgroup',
            name='platform',
            field=models.ForeignKey(blank=True, db_column='platform', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nagios.NagiosPlatform'),
        ),
        migrations.AlterField(
            model_name='nagiosservers',
            name='platform',
            field=models.ForeignKey(blank=True, db_column='platform', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nagios.NagiosPlatform'),
        ),
        migrations.DeleteModel(
            name='NagiosPlatforms',
        ),
    ]
