# Generated by Django 2.2.4 on 2019-09-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagios', '0007_auto_20190901_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagiosservice',
            name='active_checks_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nagiosservice',
            name='notifications_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nagiosservice',
            name='passive_checks_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
