# Generated by Django 2.2.4 on 2019-09-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0003_auto_20190830_1742'),
        ('nagios', '0008_auto_20190901_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nagiosservice',
            name='server',
        ),
        migrations.AddField(
            model_name='nagiosservice',
            name='device',
            field=models.ForeignKey(blank=True, db_column='server', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nagiosservices', to='dcim.Device'),
        ),
        migrations.AlterField(
            model_name='nagiosservice',
            name='use_template',
            field=models.ForeignKey(blank=True, db_column='use_template', null=True, on_delete=django.db.models.deletion.CASCADE, to='nagios.NagiosService'),
        ),
    ]
