# Generated by Django 2.2.4 on 2019-09-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0006_remove_device_observium_enabled'),
        ('nagios', '0011_auto_20190903_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagiosplatform',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nagiosplatform', to='dcim.Platform'),
        ),
    ]
