# Generated by Django 2.2.4 on 2019-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0003_auto_20190830_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='nagios_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
