# Generated by Django 2.2.4 on 2019-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0004_device_nagios_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='observium_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
