# Generated by Django 2.2.4 on 2019-09-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0005_device_observium_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='observium_enabled',
        ),
    ]
