# Generated by Django 2.2.4 on 2019-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0007_auto_20190903_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='nagios_parents',
            field=models.ManyToManyField(blank=True, related_name='_device_nagios_parents_+', to='dcim.Device'),
        ),
    ]
