# Generated by Django 2.2.4 on 2019-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0009_auto_20190918_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='nagios_enabled',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
